name: "Action Sync Extensions Version"
author: "xcvdsfd"
description: "sync extensions version info to airtable"
inputs:
  token:
    description: "Github token. E.g. secrets.GITHUB_TOKEN"
    require: false
  apiKey:
    description: "Airtable Authentication Token"
    require: true
  airtable_ext_baseid:
    description: "airtable_ext_baseid"
    default: "appiIKDIDD1CSLQgx"
  airtable_ext_tableid:
    description: "airtable_ext_tableid"
    default: "tbl5YM7NkZz6SFQM0"
  airtable_store_baseid:
    description: "airtable_store_baseid"
    default: "appfcHSwqKUfXxCOc"
  airtable_store_tableid:
    description: "airtable_store_tableid"
    default: "tblzCsHS1NcY6LLOb"
  packages:
    description: "consumers packages"
    require: false
  version:
    description: "consumers version"
    require: false
  

runs:
  using: "node20"
  main: "dist/index.js"