name: Check Consumers
on:
  workflow_dispatch:
    inputs:
      packages:
        description: 'packages'
        required: true
        type: string
      version:
        description: 'version'
        required: true
        type: string

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: trigger
        uses: kungfu-trader/action-sync-extensions-version@v1.0-alpha
        with:
          apiKey: ${{ secrets.AIRTABLE_API_KEY }}
          token: ${{ secrets.KUNGFU_GITHUB_TOKEN }}
          packages: ${{ inputs.packages }}
          version: ${{ inputs.version }}
